### ISSUE TITLE
InvalidCastException when try to post new customer with invalid parameters

### ISSUE THREAD

**Issue by daniel-leal** [balta-io/1974#2]
# Invalid Cast Exception:

Get InvalidCastException on CustomerControler(line 58), when try to post a new customer with invalid parameters.

_Can't cast "CommandResult" to "CreateCustomerCommandResult."_

# Steps to reproduce:
### Postman:

* URL: http://localhost:5000/v1/customers
* Type: POST
* Body (JSON RAW):
```
{
	"FirstName": "Daniel",
	"LastName": "12",
	"Document": "12345678911",
	"Email": "dleal@gmail.com.br",
	"Phone": "99541877"
}
```
# Stacktrace:
```
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action BaltaStore.Api.Controllers.CustomerController.Post (BaltaStore.Api) in 87869.8516ms
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action BaltaStore.Api.Controllers.CustomerController.Post (BaltaStore.Api) in 87869.8516ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidCastException: Unable to cast object of type 'BaltaStore.Domain.StoreContext.CustomerCommands.Inputs.CommandResult' to type 'BaltaStore.Domain.StoreContext.CustomerCommands.Inputs.CreateCustomerCommandResult'.
   at BaltaStore.Api.Controllers.CustomerController.Post(CreateCustomerCommand command) in C:\Users\dleal\Projects-Intern\dotnet\1974\BaltaStore.Api\Controllers\CustomerController.cs:line 58
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

![capturar](https://user-images.githubusercontent.com/3511128/51856466-ecc38500-2316-11e9-97cf-f49bcc62a8ea.PNG)

# My Solution
```
var result = (CreateCustomerCommandResult)_handler.Handle(command); //before
var result = (ICommandResult)_handler.Handle(command); //after
```

**Obs: However, I think this is not the best practice.**

**Comment by andrebaltieri** [comment]
@daniel-leal muito obrigado pelo feedback! Vai ajudar muito o pessoal <3
